### ISSUE TITLE
Unable to find package ILLink.Tasks

### ISSUE THREAD

**Issue by DJJones66** [mbpictures/GameUpdater#1]
I have tried a few things to resolve this but with no success, maybe you can provide some insight?

Unable to find package ILLink.Tasks. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	GameUpdater	GameUpdater.csproj	1	

Thanks

**Comment by PinyaGit** [comment]
Were you able to solve this problem?

**Comment by mbpictures** [comment]
Hi thanks for reporting this Issum and appologies for late reply! Can you please provide some insights about your dev Environment (OS, dotnet Version, IDE, etc)?

**Comment by PinyaGit** [comment]
win11
Visual 2019 (also tried 2022)
dotnet Version (is the same as the one used to create the updater)

it's more about the fact that this package can't be found

up:
I think I'd better describe step by step what I'm doing to find a solution to the problem as soon as I'm free. But the main problem is in ILLink.Tasks

**Comment by PinyaGit** [comment]
simulate the situation that I don't have any IDEs and stuff at all. I deleted everything.

1) https://github.com/mbpictures/GameUpdater
download the code and unzip it into the directory -> C:\Launcher\GameUpdater-master

2) download the IDE. Let's try to use Visual Studio 2022, clean installation with no workloads.

3) open GameUpdater.sln

4) Visual Studio complains that Wix is missing, so install it from here:
https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2022Extension

5) open GameUpdater.sln again

6) Visual says to install the .NET workload -> agree and install

7) the project is restarted by itself and an error appears that the project is designed for .NET, which is not installed

8) Click Install - Run Environment .NET Core 3.1 (LTS)

9) The project restarts and there are no more errors other than dependencies ILLink.Tasls 0.1.4-preview-981901
GameUpdater -> Dependencies -> Packages -> ILLink.Tasls 0.1.4-preview-981901

10) to update the package or to download it - it is not possible. Running a debug gets an error

Error	NU1101	The ILLink.Tasks package could not be found. Packages with this identifier do not exist in the following package sources: Microsoft Visual Studio Offline Packages, nuget.org	GameUpdater	C:\Launcher\GameUpdater-master\GameUpdater\GameUpdater.csproj	1	

If I'm doing something wrong, I hope for your feedback. I have not found any other launcher with the functionality I need (without the zip file)

nuget.org	and Offline Packages are not aware of the existence of such a package

**Comment by DJJones66** [comment]
Chiming in, I was not able to solve this issue.  If I recall I tried on both 2019 and 2022 and also installed Wix from the market.

I will try it again as soon as I get a moment free to refresh myself but we have basically the same process with the same outcome.

**Comment by DJJones66** [comment]
I will try this on my other system to verify a few things but for some strange reason, this compiled and got to something new, An exception because the GameUpdater.ini is missing?

**Comment by PinyaGit** [comment]
[GameUpdater.ini](https://github.com/mbpictures/GameUpdater/blob/master/GameUpdater/GameUpdater.ini)

But it is in the folder

**Comment by DJJones66** [comment]
> [GameUpdater.ini](https://github.com/mbpictures/GameUpdater/blob/master/GameUpdater/GameUpdater.ini)
> 
> But it is in the folder

Thank you, I checked everywhere but there.  Just kind of shocked this suddenly is getting further than I had experienced before and trying to figure out what I have installed over the last few months that would of resolved the issue.

**Comment by PinyaGit** [comment]
> 

I hope you find it. Otherwise I will have to check on another OS in a virtual machine. Who knows how it works...

**Comment by DJJones66** [comment]
Off the top of my head I think I had to install the MS Visual C++ 2012 Redist (x64) due to a missing dll issue I had with something else I was doing.  So I wonder given that time frame and this being the only project I have that uses Wix is if that is the issue perhaps.  It will take a little, probably not today, to test this theory out though.

**Comment by PinyaGit** [comment]
> Off the top of my head I think I had to install the MS Visual C++ 2012 Redist (x64) due to a missing dll issue I had with something else I was doing. So I wonder given that time frame and this being the only project I have that uses Wix is if that is the issue perhaps. It will take a little, probably not today, to test this theory out though.

they are installed

**Comment by DJJones66** [comment]
Good news or bad news depending on how you look at it, my other system has the ILLink.Task issue.   So now the question is how did I solve this?

**Comment by DJJones66** [comment]
I used both VS 2019/2022.  They are up to date.  I had to install the Wix tools and extensions for both VS Installs.  Let me think on this and see if I can find a difference between the 2 systems.

**Comment by DJJones66** [comment]
I found the difference, I was playing around with it since there was no reply and I simply removed the line in GameUpdater.csproj it looks like.  Not the first found projects with strange stuff in it that had to be removed. No clue as to the overall results but does seem to run now.

**Comment by DJJones66** [comment]
Here is the issue line in GameUpdater.csproj:

<PackageReference Include="ILLink.Tasks" Version="0.1.4-preview-981901" />

The problem is the package does not exist.

**Comment by PinyaGit** [comment]
u remove     PackageReference Include="ILLink.Tasks" Version="0.1.4-preview-981901" ???

in GameUpdater.csproj

**Comment by PinyaGit** [comment]
PackageReference Include="ILLink.Tasks" Version="0.1.4-preview-981901"

**Comment by PinyaGit** [comment]
![изображение](https://user-images.githubusercontent.com/39755512/176307364-3512cf02-c157-449b-b1b2-78f4c95b9acb.png)

removing the line yes - an exception appears, but it is not a solution to the problem.

**Comment by PinyaGit** [comment]
Oh no, I must be wrong. Manually putting the ini file into this folder returns a 404 error. I think it will work! just need to configure the server.

System.Net.WebException: "The remote server returned an error: (404) Not Found."

**Comment by mbpictures** [comment]
Hi again!

So @PinyaGit can you verify the issue is gone using the version of [this PR](https://github.com/mbpictures/GameUpdater/pull/2)?

**Comment by PinyaGit** [comment]
> So @PinyaGit can you verify the issue is gone using the version of [this PR](https://github.com/mbpictures/GameUpdater/pull/2)?

I'll give it a try, but right now I'm trying to figure out how to build a manifest.

**Comment by PinyaGit** [comment]
Oh yes, we did that earlier. Now I'm in the process of contacting the server where the xml should be

**Comment by PinyaGit** [comment]
in general, the process went further.  Now I am required to generate an update file and put it on the server.  Probably after that, the launcher should start normally.  but this does not mean that the error will not manifest itself later.  further, it is a little unclear to me how to make xml if I do not have earlier versions.  this is my first version of the client and it does not depend on the previous ones.  it would be nice to get an example of writing

but I will read it in the morning.  the night is for sleeping.  I'll write more instructions in the morning.

**Comment by DJJones66** [comment]
> in general, the process went further. Now I am required to generate an update file and put it on the server. Probably after that, the launcher should start normally. but this does not mean that the error will not manifest itself later. further, it is a little unclear to me how to make xml if I do not have earlier versions. this is my first version of the client and it does not depend on the previous ones. it would be nice to get an example of writing
> 
> but I will read it in the morning. the night is for sleeping. I'll write more instructions in the morning.

Yes, I am kind of in the same boat as well.  Beyond the package issue and trying to piece together what is needed to get this working.

**Comment by PinyaGit** [comment]
![изображение](https://user-images.githubusercontent.com/39755512/176362491-1ebced5c-eaf0-4597-a70e-27887c0bd88e.png)
With what parameters is it correct to run this tool?

**Comment by PinyaGit** [comment]
> With what parameters is it correct to run this tool?

ManifestTool.exe -f C:\wamp64\www\flappy_files\ -v 1.0.1 -d 1.0.0 -u http://url/flappy_files/Flappy%20Skyrim/

also update.xml u need to put tool folder

UP: tool really doesn't like spaces in the path. i'll generate an update and report on working without this dependency.

**Comment by PinyaGit** [comment]
![изображение](https://user-images.githubusercontent.com/39755512/176388401-8cdb9ad5-d951-49b0-b9b7-f516803364ad.png)
![изображение](https://user-images.githubusercontent.com/39755512/176388544-bfcc32e3-c6cd-490a-a1e7-09771f881e84.png)


something is not right. I can't add my project or just Doom. Error programs.cs
@mbpictures

**Comment by mbpictures** [comment]
> ![изображение](https://user-images.githubusercontent.com/39755512/176362491-1ebced5c-eaf0-4597-a70e-27887c0bd88e.png) With what parameters is it correct to run this tool?

For the first, you don't have to provide the -d Parameter as this is the version where your next version depends on (and the first version, has no dependency)

@PinyaGit is it possible you are using an existing XML file without a patch Element inside it?

**Comment by mbpictures** [comment]
Additionally: paths containing spaces have to be wrapped in quotation marks

**Comment by PinyaGit** [comment]
> For the first, you don't have to provide the -d Parameter as this is the version where your next version depends on (and the first version, has no dependency)

without the -d parameter, the program simply will not start. This is a Required parameter
![изображение](https://user-images.githubusercontent.com/39755512/176417373-17b08f3e-e695-4d5e-af17-ac9ba7171b5b.png)

I used the update.xml from the repository
https://github.com/mbpictures/GameUpdater/blob/master/GameUpdater/update.xml

UP:
should I describe step by step how I try to use the tools?

**Comment by DJJones66** [comment]
I have yet to play with it since we have got past the OP issue but want to ask, if the -d option is required how is this handled on the original install when there is nothing prior?  

I figure based on reading I want to ask my odd questions so if someone else comes along and has issues they may be able to use all this to work through them.

**Comment by mbpictures** [comment]
You can try this command to get it working:
```
ManifestTool.exe -f YOUR_FOLDER -v 1.0.0 -d 0.0.0 -u http://YOUR_URL.COM
```
As this seems kinda hacky and I don't know anymore what was the idea behind it, I'll investigate how to remove the -d param for the first version and update you soon!

**Comment by PinyaGit** [comment]
![изображение](https://user-images.githubusercontent.com/39755512/176439576-84f609b9-723c-4af0-a043-fb8a0b3d7074.png)
YAY! this works if you do not use the update.xml file at all. I'm going to try it on a big folder.

**Comment by mbpictures** [comment]
Glad to help. You can try [this pr](https://github.com/mbpictures/GameUpdater/pull/3) to use the tool without the parameter -d. I'm having issues with the GameUpdater and it won't launch. Does it work on your system?

**Comment by PinyaGit** [comment]
we are gradually approaching a solution. The xml was generated, through the visual, the launcher starts, But it freezes.

make a build of the project does not work (installer and updater)

Put ini file already built program in the bin folder - just does not start.
![изображение](https://user-images.githubusercontent.com/39755512/176448894-cd6c6de2-116a-4249-b576-ea7390d80491.png)
![изображение](https://user-images.githubusercontent.com/39755512/176449572-22cd837e-614a-42b0-b6dd-60086441353b.png)

**Comment by DJJones66** [comment]
> Glad to help. You can try [this pr](https://github.com/mbpictures/GameUpdater/pull/3) to use the tool without the parameter -d. I'm having issues with the GameUpdater and it won't launch. Does it work on your system?

It wouldn't on mine either but I assumed at the time it was my issue there (guess not)

**Comment by mbpictures** [comment]
Update: [PR 3](https://github.com/mbpictures/GameUpdater/pull/3) should fix the issue. Try it again and let me know, if it's working!

EDIT: Don't forget to copy the .ini file inside your build folder (next to the GameUpdater.exe)

**Comment by PinyaGit** [comment]
![изображение](https://user-images.githubusercontent.com/39755512/176484540-3c47f915-bc17-4924-8bde-93125c9ea917.png)

Strangely enough, nothing has changed. This is not critical, you can add to the instructions about -d 0.0.0 but run the launcher correctly still failed.

P.S. Sure i ```dotnet build``` new one

**Comment by mbpictures** [comment]
Try to clear your local bin folder inside the ManifestTool folder.

Have you tried the provided default .ini config? This uses a manifest file on my server and should definitely work.
EDIT: don't forget to rebuild the GameUpdater project

**Comment by PinyaGit** [comment]
> Have you tried the provided default .ini config? This uses a manifest file on my server and should definitely work.

gimme sec

**Comment by PinyaGit** [comment]
yep... After clearing the bin folder, it works without the -d parameter

My fault for not finding how to build the installer and updater, it is written directly in the description. I'll try to put it all together now.

**Comment by PinyaGit** [comment]
![изображение](https://user-images.githubusercontent.com/39755512/176493561-c6b81410-01ce-45ef-8e3c-f469bed1548d.png)
![изображение](https://user-images.githubusercontent.com/39755512/176494282-708111f0-6175-4d0f-b4f7-215b1a1dcf33.png)


I can't figure it out. It seems to work, or not. file check freeze, sees 0 files.

**Comment by PinyaGit** [comment]
And I tried to build a launcher to run without visuals. the error appears red

**Comment by DJJones66** [comment]
If I had to guess this is part of the ILLink package dealing with Tasks.

**Comment by PinyaGit** [comment]
ok...ok Let's try how it works for you.

I deleted the repository completely and unpacked it again

copy the ini file to GameUpdater\bin\Debug\netcoreapp3.1\

Run GameUpdater.exe

 <- Check Files /// check test folder ->

![изображение](https://user-images.githubusercontent.com/39755512/176496135-b9a49c65-29d3-41d7-8cf3-fde7514fdaa7.png)

**Comment by DJJones66** [comment]
I think I have found the issue with regard to ILLink.Task.  Seems it does not work for this version Core 3.1, while not tested I think it is only for .Net 5 and 6.  

For some reason the packages that existed when this was created 2 years ago are no longer in existence, I have found a few articles referencing them as well and the information provided is no longer around.  I am not sure if this is used for how the installer works and probably more with the Wix stuff (Never used it so have nothing but a guess there)

**Comment by PinyaGit** [comment]
Wix is only used in visuals. The project must then be built via ```dotnet publish``` as I understand it.

I'm just wondering why he's not downloading

**Comment by mbpictures** [comment]
The code of the file checking had a stupid bug (sorry for that!) and is now fixed with [pr4](https://github.com/mbpictures/GameUpdater/pull/4) (already merged).

**Comment by PinyaGit** [comment]
@mbpictures 

I just found another fix. you need to change the reference in nuget.config

https://dotnet.myget.org/F/dotnet-core/api/v3/index.json  ----> https://api.nuget.org/v3/index.json

then dotnet publish will work

**Comment by PinyaGit** [comment]
@mbpictures sry but... something new broken now :D

![изображение](https://user-images.githubusercontent.com/39755512/176540832-e79a103f-06b7-4797-b672-c889c5c89686.png)

**Comment by PinyaGit** [comment]
if i remove this 2 lines. download work's correctly

and repair work too D:

UP: just remove .0 in 100.0

**Comment by mbpictures** [comment]
Okay it's working on my side... but I'll remove the .0 just in case.
Let me know if you have further bugs and issues. If this issue is solved, I'll close it soon.

**Comment by PinyaGit** [comment]
Yes, I'll try to build it all together now. Thank you so much for not forgetting about this project D:
